NgoThanhTien_2001200542_WebKFC/Controllers/NhanVienController.cs
using NgoThanhTien_2001200542_WebKFC.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace NgoThanhTien_2001200542_WebKFC.Controllers
{
    public class NhanVienController : Controller
    {
        dbWebGaRanKFCDataContext data = new dbWebGaRanKFCDataContext();

        // GET: NhanVien
        public ActionResult index()
        {
            List<tbl_MonAn> lstma = data.tbl_MonAns.ToList(); 
            return View(lstma);
        }
        public ActionResult CreatesMonAn()
        {
            ViewBag.maLoai = new SelectList(data.tbl_Loais.ToList().OrderBy(n => n.TenLoai), "maLoai", "TenLoai");
            return View();
        }
        [HttpPost]
        public ActionResult CreatesMonAn(tbl_MonAn ma, HttpPostedFileBase fileupload)
        {
            var fileName = Path.GetFileName(fileupload.FileName);
            var path = Path.Combine(Server.MapPath("~/Hinhanh"), fileName);
            fileupload.SaveAs(path);
            ma.Images = fileName;
            data.tbl_MonAns.InsertOnSubmit(ma);
            data.SubmitChanges();
            return RedirectToAction("Index");
        }
        public ActionResult DeleteMonAn(int id)
        {
            tbl_MonAn ma = data.tbl_MonAns.Single(dk=> dk.id == id);
            data.tbl_MonAns.DeleteOnSubmit(ma);
            data.SubmitChanges();
            return RedirectToAction("index") ;
        }

        public ActionResult UpdateMonAn(int id)
        {
            ViewBag.maLoai = new SelectList(data.tbl_Loais.ToList().OrderBy(n => n.TenLoai), "maLoai", "TenLoai");
            tbl_MonAn ma = data.tbl_MonAns.SingleOrDefault(dk=> dk.id == id);
            return View(ma);
        }
        [HttpPost]
        public ActionResult UpdateMonAn(tbl_MonAn ma, HttpPostedFileBase fileupload)
        {
            if(fileupload == null)
            {
                ViewBag.ThongBao = "Vui lòng chọn ảnh bìa";
                return View();
            }    
            var fileName = Path.GetFileName(fileupload.FileName);
            var path = Path.Combine(Server.MapPath("~/Hinhanh"), fileName);
            fileupload.SaveAs(path);
            ma.Images = fileName;
            UpdateModel(ma);
            data.SubmitChanges();
            return RedirectToAction("index");
        }
        public ActionResult QLLoai()
        {
            return View();
        }
    }
}

NgoThanhTien_2001200542_WebKFC/Views/NhanVien/CreatesMonAn.cshtml
@model NgoThanhTien_2001200542_WebKFC.Models.tbl_MonAn

@{
    ViewBag.Title = "CreatesMonAn";
    Layout = "~/Views/Shared/_LayoutPage2.cshtml";
}

<h2>THÊM MÓN ĂN</h2>

@using (Html.BeginForm("CreatesMonAn", "NhanVien", FormMethod.Post, new { @enctype = "multipart/form-data" }))
{     
    @Html.AntiForgeryToken()
<div class="container">
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            <label>Tên món ăn</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label>Mô tả</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label>Giá bán</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label>Hình ảnh</label>
            <div class="col-md-10">
                <input type="file" name="fileupload" />
            </div>
        </div>

        <div class="form-group">
            <label>Đơn vị</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.DonViTinh, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DonViTinh, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label>Loại</label>
            <div class="col-md-10">
                @Html.DropDownList("maLoai")
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input style="margin: 30px" type="submit" value="Create" class="btn btn-sm btn-primary" />
            </div>
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

NgoThanhTien_2001200542_WebKFC/Views/NhanVien/DeleteMonAn.cshtml
@model NgoThanhTien_2001200542_WebKFC.Models.tbl_MonAn

@{
    ViewBag.Title = "DeleteMonAn";
    Layout = "~/Views/Shared/_LayoutPage2.cshtml";
}

<h2>DeleteMonAn</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>tbl_MonAn</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Price)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Price)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Images)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Images)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DonViTinh)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DonViTinh)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.maLoai)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.maLoai)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

NgoThanhTien_2001200542_WebKFC/Views/NhanVien/QLLoai.cshtml
@{
    ViewBag.Title = "QLLoai";
    Layout = "~/Views/Shared/_LayoutPage2.cshtml";
}

<h2>QLLoai</h2>

NgoThanhTien_2001200542_WebKFC/Views/NhanVien/UpdateMonAn.cshtml
@model NgoThanhTien_2001200542_WebKFC.Models.tbl_MonAn
@{
    ViewBag.Title = "UpdateMonAn";
    Layout = "~/Views/Shared/_LayoutPage2.cshtml";
}

<div class="container-fluid">
    <h2>Thông tin sản phẩm</h2>
    @if (ViewBag.success != null)
    {
        @ViewBag.success
    }
    @using (Html.BeginForm("UpdateMonAn", "NhanVien", FormMethod.Post, new { @enctype = "multipart/form-data" }))
    {
        @Html.AntiForgeryToken()
        @Html.ValidationSummary(true)
<div class="container">
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            <label>Mã món ăn</label>
            <div class="col-md-10">
               <div>@Model.id</div>
            </div>
        </div>
        <div class="form-group">
            <label>Tên món ăn</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label>Mô tả</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label>Giá bán</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label>Hình ảnh</label>
            <div class="col-md-10">
                <input type="file" name="fileupload" />
                <img src="@Url.Content("~/Hinhanh/" + Model.Images)" width="30%" />(Ảnh hiện tại)
            </div>
        </div>

        <div class="form-group">
            <label>Đơn vị</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.DonViTinh, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DonViTinh, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label>Loại</label>
            <div class="col-md-10">
                @Html.DropDownList("maLoai")
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input style="margin: 30px" type="submit" value="Cập nhật" class="btn btn-sm btn-success" />
            </div>
        </div>
    </div>
</div>

    }
</div>
<div>
    @Html.ActionLink("Back to List", "Index")
</div>

NgoThanhTien_2001200542_WebKFC/Views/NhanVien/index.cshtml
@using NgoThanhTien_2001200542_WebKFC.Models;
@model List<tbl_MonAn>
@{
    ViewBag.Title = "index";
    Layout = "~/Views/Shared/_LayoutPage2.cshtml";
}

<div class="container-fluid">
    <h2>DANH SÁCH MÓN ĂN</h2>
    <a href="/NhanVien/CreatesMonAn" class="btn btn-sm btn-primary">Thêm mới</a>
        <table class="table">
            <tr>
                <th>Mã món ăn</th>
                <th>Tên món ăn</th>
                <th>Ảnh</th>
                <th>Đơn giá</th>
                <th>Mô tả</th>
                <th>Đơn vị</th>
                <th></th>
            </tr>
            
                @foreach (var item in Model)
                {
                    <tr>
                        <td width="15%">@item.id</td>
                        <td width="15%">@item.Name</td>
                        <td width="20%"><img width="50%" src="~/HinhAnh/@item.Images" /></td>
                        <td width="10%">@string.Format("{0:0,0}", @item.Price) VND</td>
                        <td width="15%">@item.Description</td>
                        <td width="15%">@item.DonViTinh</td>
                        <td>
                            <a class="btn btn-sm btn-danger" onclick="alert('Xóa món ăn thành công');"
                               href="/NhanVien/DeleteMonAn/@item.id">Xóa</a>
                            <a class="btn btn-sm btn-success" href="/NhanVien/UpdateMonAn/@item.id">Cập nhật</a>
                        </td>
                    </tr>
                }
        </table>
</div>